# Generated by Django 4.1.2 on 2022-10-24 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="day",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Sunday"),
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="routine",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(4)],
                verbose_name="Routine Name",
            ),
        ),
    ]
