# Generated by Django 4.1.2 on 2022-10-24 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routine", "0002_alter_class_day_alter_routine_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routine",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=110,
                null=True,
                validators=[django.core.validators.MinLengthValidator(4)],
            ),
        ),
    ]
